### ISSUE TITLE
IndexError when parsing predictor variables for PyRateMBD

### ISSUE THREAD

**Issue by bmchorse** [dsilvestro/PyRate#14]
I previously ran PyRateMBD with the time column counting down (e.g. 55, 54, 53...), but it appears from the tutorial and the variable trajectories obtained by plotting that time should instead be counting up (0, 1, 2...).

However, when I corrected my predictor files to do so (very small -n for testing), I get the following error:

![error](https://user-images.githubusercontent.com/20344778/37556192-e71a78d6-29c8-11e8-8cce-081ff1bb3fce.JPG)

Here is the example format of one of the predictor files, with middle data stripped out for brevity:

```
time	artiodactyla
0	130
1	121
2	124
3	115
...	...
51	10.5
52	11
```

**Comment by dsilvestro** [comment]
Thanks for spotting that! The error message (admittedly cryptic) was returned when the variables did not include a value at time 0. This is now fixed in the new [lib_DD_likelihood.py file](https://github.com/dsilvestro/PyRate/blob/master/pyrate_lib/lib_DD_likelihood.py). PyRate will now extend the most recent value to the present time (or to the time of extinction of the clade) when necessary. Hopefully this solves the issue.

**Comment by bmchorse** [comment]
Excellent, this seems to have fixed it! Thank you.
