### ISSUE TITLE
How to deal with multiple fossils for the same species, including when they have different MinAge and MaxAge?

### ISSUE THREAD

**Issue by jamie-thompson** [dsilvestro/PyRate#36]
I have multiple examples of the same species in my dataset.  Where the MinAge and MaxAge are the same, should I delete duplicates?  Where they are different, do I summarise with the youngest MinAge and oldest MaxAge?  Sorry if this is explained or obvious.

**Comment by dsilvestro** [comment]
I would keep them if they come from different localities but remove them as duplicates otherwise. Their ages will be resampled randomly from their min/max age range when you [prepare the input file using pyrate_utilities.r](https://github.com/dsilvestro/PyRate/blob/master/tutorials/pyrate_tutorial_1.md#generate-pyrate-input-file-option-2). I hope this helps!
