### ISSUE TITLE
Error plotting MBD results: numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 0

### ISSUE THREAD

**Issue by LauravanHolstein** [dsilvestro/PyRate#41]
Hi! 

Final question for now (I hope!). I got the following error while trying to plot the results of a MBD analysis: 

<img width="821" alt="Screenshot 2023-07-24 at 13 57 22" src="https://github.com/dsilvestro/PyRate/assets/44289403/4b1d3dc5-5c0a-40c8-bbd0-4f074e3f5be8">

I'm running PyRate on a Mac M1, and these are the [data](https://github.com/dsilvestro/PyRate/files/12145835/Error.numpy.zip) (although I got the same error with a different dataset, so unlikely this is the consequence of weird data input). 

Also, just to check my sanity, in Tracer the Gl0_0 estimate refers to the correlation parameter for self diversity dependence of speciation (and Wl0_0 to the shrinkage factor for self diversity dependence of speciation, etc), right? With the ...0_1, ...0_2, etc, estimates referring to parameters for supplied predictors 1, 2, etc?

The reason I ask is that, when I ran MBD with a single predictor, the LTT output of the whole clade, I got very different correlation parameters for Gl0_0 and Gl0_1 (-8.31 and 1.62, respectively). I assumed that these would be the same or similar, as GI0_1 would essentially be self diversity dependence in this case, right? I must be understanding it wrong! 

Many thanks, 
Laura

**Comment by thauffe** [comment]
Hi Laura,

This error caused by the latest numpy version has been already fixed a week ago. Please download the latest PyRate version.

Your understanding is correct: Self diversity dependence is always indicated by 0_0, i.e. Gl0_0, Wl0_0, Gm0_0, and Wm0_0.
Gl0_1 can never be diversity dependence. 
How did you run the MBD analysis with the LTT as single predictor? The only possibility to do so is an empty folder for `-var`. Then, correctly, you do not get any Gl0_1 because self diversity is the only predictor.

Best,
Torsten
