### ISSUE TITLE
Error combining log files

### ISSUE THREAD

**Issue by LauravanHolstein** [dsilvestro/PyRate#42]
Hi again! 

Here I am with another error... again, on a Mac M1, and with PyRate and numpy fully up-to-date. When combining log files across 10 replicates (with preservation prior TPP), I run into the following error: 

<img width="693" alt="Screenshot 2023-08-07 at 10 10 27" src="https://github.com/dsilvestro/PyRate/assets/44289403/492cd654-792b-438b-bef0-9a27c90eabb3">

Any ideas would be appreciated! 

Best wishes, 
Laura

**Comment by thauffe** [comment]
Hi Laura,

1. Better use the -logCombRJ instead of -logComb when you aim to combine the output of RJMCMC analyses
2. The root of the problem is that the number of columns in the _mcmc.log_ files differ among your replicates. The "52" and "50" on your screenshot _(9901, 52)_ indicate the number of rows and columns. In comparison to replicates 1 and 10, replicate 2 misses either one species or two shift points of sampling rate (-qtimes). 

Hopefully this solves the error!

**Comment by LauravanHolstein** [comment]
You are truly my PyRate guardian angel - thank you once again for a flawless fix!
