### ISSUE TITLE
Compiling and Installing FastPyRateC Library Requires Depricated 'distutils' Module

### ISSUE THREAD

**Issue by supersnes1** [dsilvestro/PyRate#44]
I have been attempting to compile and install FastPyRateC to run analyses using python 3.12 on a Macbook with an intel processor.  I have followed the tutorial and entered the line: python3 setup.py build.  I keep receiving an error that states "ModuleNotFoundError: No module named 'distutils'".  I looked into manually installing distutils but it seems that it is now deprecated and removed as of python 3.12.  Is there a workaround at this time?  I will look into using an earlier version of python 3.x to see if that helps in the meantime.

Thanks in advance

**Comment by thauffe** [comment]
Hi,

Thanks for reporting this issue.
 
Why do you try to compile the FastPyRateC library? Is the pre-compiled library not working on your system? In general, it is recommended to use the install.sh bash script because it automatizes all steps.

I modified _setup.py_ and _install.sh_ and the compilation works on my Linux system. Could you please place them in your _PyRate/pyrate_lib/fastPyRateC/ModulePyrateC_ folder and try them on your Mac with python 3.12?

Best,
Torsten


[Compile.zip](https://github.com/dsilvestro/PyRate/files/13706732/Compile.zip)

**Comment by supersnes1** [comment]
Torsten,

I was able to run PyRate but I was given the message "Module FastPyRateC was not found" despite my PyRate-master directory did containing files for the module.  I was attempting to reinstall it to see if that could troubleshoot the issue.  I copied your newer files over and attempted to compile again but I continued to receive the module not found error.  However, I began to get a new warning message claiming that the module is not from a known/safe source.  I set the module to be allowed for the time being and it now works as intended.

Thank you for your time, I greatly appreciate your assistance.
